[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
txhedge = "BZ6W4B9Te3nnZWXd19QSaTXDxTF1rtC1je8roTDrorrk"

[programs.devnet]
txhedge = "BZ6W4B9Te3nnZWXd19QSaTXDxTF1rtC1je8roTDrorrk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/**/*.ts"
